//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStoreApi.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public App()
        {
            this.LicensedApps = new HashSet<LicensedApp>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<LicensedApp> LicensedApps { get; set; }
    }
}
