//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStoreApi.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationStoreDBEntities : DbContext
    {
        public ApplicationStoreDBEntities()
            : base("name=ApplicationStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<App> Apps { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerLicens> CustomerLicenses { get; set; }
        public DbSet<License> Licenses { get; set; }
        public DbSet<LicensedApp> LicensedApps { get; set; }
    }
}
