//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStoreApi.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicensedApp
    {
        public int Id { get; set; }
        public int AppId { get; set; }
        public int LicenseId { get; set; }
    
        public virtual App App { get; set; }
        public virtual License License { get; set; }
    }
}
